x-minio-environment: &minio-environment
  MINIO_ROOT_USER: miniouser
  AWS_ACCESS_KEY_ID: miniouser
  MINIO_ROOT_PASSWORD: miniopassword
  AWS_SECRET_ACCESS_KEY: miniopassword

services:
  minio:
    image: minio/minio:RELEASE.2024-06-11T03-13-30Z
    command: server /data --console-address ":9001"
    environment:
      <<: *minio-environment
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: curl --fail http://localhost:9001
      interval: 1s
      timeout: 1s
      retries: 3

  minio-sample-loader:
    image: minio/mc:RELEASE.2024-06-12T14-34-03Z
    entrypoint: /bin/bash /entrypoint.sh
    environment:
      <<: *minio-environment
    volumes:
      - "./docker/minio/mc/entrypoint.sh:/entrypoint.sh:ro"
      - "./data/STAC/sample/data/:/stac/sample:ro"
      - "./data/COG/sample/data/:/cog/sample:ro"
    depends_on:
      minio:
        condition: service_healthy
    command: mc cp --recursive /stac/sample minio/stac && mc cp --recursive /cog/sample minio/cog

  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - WORKERS_PER_CORE=1

  mapproxy:
    image: ghcr.io/mapproxy/mapproxy/mapproxy:2.1.1-dev
    ports:
        - "8080:8080"
