x-minio-environment: &minio-environment
  MINIO_ROOT_USER: miniouser
  AWS_ACCESS_KEY_ID: miniouser
  MINIO_ROOT_PASSWORD: miniopassword
  AWS_SECRET_ACCESS_KEY: miniopassword

services:
  minio:
    image: minio/minio:RELEASE.2024-06-11T03-13-30Z
    command: server /data --console-address ":9001"
    environment:
      <<: *minio-environment
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: curl --fail http://localhost:9001
      interval: 1s
      timeout: 1s
      retries: 3

#  titiler:
#    image: ghcr.io/developmentseed/titiler:latest
#    depends_on:
#      minio:
#        condition: service_completed_successfully


#  mapproxy:
#    image: ghcr.io/mapproxy/mapproxy/mapproxy:2.1.1-dev
#    depends_on:
#      titiler:
#        condition: service_completed_successfully
#    ports:
#        - "8080:8080"
#    command:
#        docker run --rm --name "mapproxy" -p 8080:8080 -t -v `pwd`/mapproxyconfig:/mapproxy/config ghcr.io/mapproxy/mapproxy/mapproxy:2.1.1-dev
